// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 40);
}

function formatAnswers(answers) {
  if (!answers || !Object.keys(answers).length) return "_No answers recorded._";
  return Object.entries(answers).map(([k, v]) => `- **${k}:** ${v}`).join("\n");
}

// ---------------------------------------------------------------------------
// Mode detection — mirrors IdeaDoctor.jsx keywords so generate.js can route
// without needing to import a React component module.
// ---------------------------------------------------------------------------
const GAME_KW    = ["game","gaming","arcade","platformer","puzzle","shooter","fps","rpg","rts","mmorpg","mmo","indie game","mobile game","endless runner","tower defense","battle royale","side scroller","top-down","roguelike","roguelite","dungeon crawler","card game","board game","strategy game","simulation game","clicker","idle game","fighting game","racing game","sports game","sandbox game","survival game","horror game","metroidvania","action game","adventure game","level design","levels","leaderboard","lives","health bar","respawn","powerup","power-up","boss fight","spawn","enemy","npc","sprite","pixel art","tilemap","physics engine","game engine","phaser","canvas game","webgl game","three.js game","2d game","3d game"];
const WEBSITE_KW = ["website","landing page","homepage","portfolio","personal site","blog","brochure site","marketing site","static site","content site","company website","business website","showcase","presentation site","web presence","online presence","micro site","one-pager","one page site","info site","informational site","lead gen site","agency site"];
const WEBAPP_KW  = ["web app","web application","saas","platform","dashboard","user account","user accounts","login","sign up","sign in","log in","register","authentication","auth","sign-in","sign-up","database","postgresql","mysql","mongodb","users can","members","membership","subscription","checkout","payment","stripe","billing","admin panel","user profile","profile page","notifications","feed","activity","collaboration","api","backend","server","real-time","realtime"];

function detectMode(text) {
  const lower = (text ?? "").toLowerCase();
  if (GAME_KW.some(k => lower.includes(k)))    return "game";
  if (WEBSITE_KW.some(k => lower.includes(k))) return "website";
  if (WEBAPP_KW.some(k => lower.includes(k)))  return "webapp";
  return "standard";
}

// ---------------------------------------------------------------------------
// STANDARD app fallback
// ---------------------------------------------------------------------------
function buildFallbackSpecPack(project) {
  const { ideaText, analysis, answers } = project;
  const appType = analysis?.appMeta?.label ?? "Custom App";
  const icon    = analysis?.appMeta?.icon   ?? "💡";
  const slug    = slugify(ideaText || "my-project");

  return {
    "SPEC.md":       `# SPEC.md — Project Specification\n\n## ${icon} App Type\n**${appType}**\n\n## 🎯 Core Idea\n${ideaText}\n\n## ⚠️ Hidden Complexity Warning\n${analysis?.warning ?? "_None identified._"}\n\n## ✅ Clarification Answers\n${formatAnswers(answers)}\n\n## 🏗️ Summary\n${analysis?.summary ?? "_Pending._"}\n\n---\n_Generated by Project Brain (offline fallback)._\n`,
    "RULES.md":      `# RULES.md — Project Constraints\n\n## Scope\n- Build only what is defined in SPEC.md.\n- Do not add unscoped features.\n\n## Stack\n- App Type: **${appType}**\n- Frontend: React + Vite + Tailwind CSS\n- Backend: Node.js / Express\n- AI: Replit AI Integrations\n\n## Quality Gates\n- No feature ships without a TEST_PLAN entry.\n- All routes must be in APP_MAP.md.\n`,
    "BUILD_PLAN.md": `# BUILD_PLAN.md — Build Roadmap\n\n## Phase 1 — Foundation ✅\n- [x] Project setup and core layout\n- [x] Idea Doctor flow\n\n## Phase 2 — Core Features (Current)\n- [ ] Primary data model\n- [ ] Core user flow\n- [ ] Backend API routes\n\n## Phase 3 — Polish\n- [ ] Error states and loading states\n- [ ] Mobile responsiveness\n\n## Phase 4 — Ship\n- [ ] Tests passing\n- [ ] Deploy via Replit Deployments\n`,
    "TEST_PLAN.md":  `# TEST_PLAN.md — Testing Strategy\n\n## Unit Tests\n- [ ] Core data transformation functions\n- [ ] API input validation\n\n## E2E (Playwright)\n- [ ] Happy path: complete idea → cockpit\n- [ ] Error states: failed API call\n`,
    "APP_MAP.md":    `# APP_MAP.md — Architecture\n\n## Frontend Routes\n| Page | Component |\n|------|-----------|\n| Landing | Landing.jsx |\n| Cockpit | App.tsx → Cockpit |\n\n## Backend API\n| Method | Route | Description |\n|--------|-------|-------------|\n| POST | /api/analyze | Classify idea |\n| POST | /api/generate | Generate spec files |\n| POST | /api/companion | AI chat & recovery |\n\n## Project Slug\n\`${slug}\`\n`,
  };
}

// ---------------------------------------------------------------------------
// GAME fallback
// ---------------------------------------------------------------------------
function buildFallbackGamePack(project) {
  const { ideaText } = project;
  const slug = slugify(ideaText || "my-game");
  return {
    "GAME_DESIGN_DOC.md":      `# GAME_DESIGN_DOC.md — Game Design Document\n\n## 🎮 Game Concept\n${ideaText}\n\n## 🎯 Core Loop\n1. Observe game state → 2. Make input decision → 3. Receive feedback → 4. Reward or consequence\n\n## ⚙️ Mechanics\n| Mechanic | Priority |\n|----------|----------|\n| Movement | P0 |\n| Core Action | P0 |\n| Feedback | P1 |\n| Progression | P2 |\n\n---\n_Generated by Project Brain Game Builder Mode (offline fallback)._\n`,
    "SYSTEMS_ARCHITECTURE.md": `# SYSTEMS_ARCHITECTURE.md — Game Systems\n\n## 🔁 Game Loop\n\`\`\`\nrequestAnimationFrame → update(dt) → render(ctx)\n\`\`\`\n\n## ⚠️ Hard Scope Rules\n- **DO NOT TOUCH the game loop** outside \`Game.js\`\n- All entity creation goes through \`EntityManager\`\n- No direct DOM manipulation from game logic\n`,
    "ASSET_LIST.md":           `# ASSET_LIST.md — Asset Checklist\n\n## 🖼️ Sprites\n- [ ] Player sprite (32×32 px)\n- [ ] Enemy sprite (24×24 px)\n- [ ] Background\n\n## 🔊 Audio\n- [ ] sfx_hit\n- [ ] sfx_score\n- [ ] sfx_gameover\n- [ ] music_main\n`,
    "FUN_TEST.md":             `# FUN_TEST.md — Is It Fun Yet?\n\n- [ ] New player understands what to do in 10 seconds\n- [ ] First input feels responsive\n- [ ] Core action is fun to repeat\n- [ ] Failure feels fair\n- [ ] No crashes after 5 minutes\n- [ ] Game over resets all state correctly\n\n## Slug\n\`${slug}\`\n`,
  };
}

// ---------------------------------------------------------------------------
// WEBSITE fallback — no backend call for website mode; templates are generated
// locally to ensure CONTENT_MAP.md + SEO_PLAN.md always have the right shape.
// ---------------------------------------------------------------------------
function buildWebsitePack(project) {
  const { ideaText, analysis, answers } = project;
  const slug    = slugify(ideaText || "my-website");
  const appType = analysis?.appMeta?.label ?? "Website";
  const icon    = analysis?.appMeta?.icon   ?? "🌐";

  return {
    "SPEC.md": `# SPEC.md — Site Specification\n\n## ${icon} Site Type\n**${appType}**\n\n## 🎯 What This Site Does\n${ideaText}\n\n## 👤 Target Audience\n${analysis?.summary ?? "_Describe who you are building this for and what they need._"}\n\n## ✅ Design & Goals Answers\n${formatAnswers(answers)}\n\n## ⚠️ Watch Out For\n${analysis?.warning ?? "_None identified._"}\n\n## 🏗️ Tech Stack\n- **Framework:** React + Vite (or plain HTML — no backend needed)\n- **Styling:** Tailwind CSS\n- **Forms:** Formspree or EmailJS (no backend)\n- **Deploy:** Vercel or Netlify (free tier)\n- **Analytics:** Plausible or Google Analytics 4\n\n---\n_Generated by Project Brain Website Mode._\n`,

    "RULES.md": `# RULES.md — Website Constraints\n\n## ✅ What This Site IS\n- A static, content-focused website\n- Deployed as a CDN-served frontend with no custom backend\n- Optimised for fast load times and SEO\n\n## ❌ What This Site is NOT (V1)\n- A web app with user accounts or authentication\n- A database-backed dynamic application\n- A real-time or collaborative tool\n\n## 🔒 Non-Negotiable Rules\n1. **No backend server** — use Formspree/EmailJS for forms, not a custom API\n2. **Mobile-first** — design for 375 px before 1280 px\n3. **One CTA per page** — never give visitors more than one primary action\n4. **Real copy before design** — no Lorem ipsum permitted in final build\n5. **Lighthouse > 90** on Performance, Accessibility, and SEO before launch\n\n## 📦 Quality Gates\n- Every page must have a unique title and meta description\n- All images must be in WebP format, under 100 KB each\n- No broken links (check with a link checker before deploy)\n`,

    "CONTENT_MAP.md": `# CONTENT_MAP.md — Content Architecture\n\n## 🗺️ Site Map\n| Page | URL | Purpose | Priority |\n|------|-----|---------|----------|\n| Home | \`/\` | First impression, convert visitors | P0 |\n| About | \`/about\` | Build trust and credibility | P0 |\n| Services / Work | \`/services\` | Show what you offer | P0 |\n| Contact | \`/contact\` | Generate leads | P1 |\n| Blog | \`/blog\` | SEO + thought leadership | P2 |\n\n## 🧩 Reusable Sections\n| Component | Appears On | Purpose |\n|-----------|------------|--------|\n| Hero | Home | Headline + primary CTA |\n| Feature Cards | Home, Services | What you offer |\n| Social Proof | Home, About | Testimonials, logos, stats |\n| CTA Block | All pages | Drive conversions |\n| Footer | All pages | Nav, contact, social links |\n\n## ✍️ Copy Hierarchy (write in this order)\n1. **Hero headline** — what you do + for whom + why now (10 words or fewer)\n2. **Primary CTA** — action-oriented ("Book a free call", not "Submit")\n3. **Social proof** — 2-3 specific testimonials with name + title\n4. **Feature descriptions** — benefit first, feature second\n5. **Meta descriptions** — 140-160 chars per page\n\n## ✅ Content Checklist\n- [ ] Hero headline tested with 3 real people — they can say back what the site does in one sentence\n- [ ] All CTAs are action-oriented verbs\n- [ ] Social proof is specific (name, title, company — not "A happy customer")\n- [ ] 404 page exists and redirects helpfully\n- [ ] No Lorem ipsum in final build\n`,

    "SEO_PLAN.md": `# SEO_PLAN.md — Search Engine Strategy\n\n## 🎯 Primary SEO Goal\nGet found by people searching for: **${ideaText.slice(0, 60)}**\n\n## 🔑 Keyword Strategy\n| Keyword Type | Example | Intent | Priority |\n|--------------|---------|--------|----------|\n| Primary | [your main service] + [location or niche] | Transactional | P0 |\n| Secondary | [specific problem] + [your solution] | Informational | P1 |\n| Branded | [your name / business name] | Navigational | P2 |\n| Long-tail | [specific question your audience Googles] | Informational | P2 |\n\n_Fill in actual keywords using Google Keyword Planner or Ahrefs Free Tools before launch._\n\n## 📋 On-Page SEO Checklist\n- [ ] Unique \`<title>\` per page (50-60 characters, primary keyword near the front)\n- [ ] Unique \`<meta description>\` per page (140-160 characters, includes CTA)\n- [ ] H1 on every page (one per page, matches title intent)\n- [ ] H2s for major sections (natural language, include secondary keywords)\n- [ ] All images have \`alt\` text describing the image content\n- [ ] Internal links: every page reachable within 2 clicks from home\n\n## 🔗 Technical SEO Checklist\n- [ ] HTTPS enabled (required for rankings)\n- [ ] \`sitemap.xml\` generated and submitted to Google Search Console\n- [ ] \`robots.txt\` configured (allow all for a public site)\n- [ ] Canonical tags set to prevent duplicate content\n- [ ] Open Graph tags (\`og:title\`, \`og:description\`, \`og:image\`) on all pages\n- [ ] Schema markup for business type (LocalBusiness, Person, etc.)\n\n## ⚡ Performance (SEO ranking factor)\n- [ ] Google Lighthouse Performance > 90 (Incognito window)\n- [ ] All images in WebP format, < 100 KB each\n- [ ] Largest Contentful Paint < 2.5 seconds\n- [ ] No render-blocking JavaScript\n- [ ] Fonts loaded with \`font-display: swap\`\n\n## 📊 Analytics & Tracking\n- [ ] Google Analytics 4 or Plausible installed\n- [ ] Conversion event tracked (form submit, CTA click, call button tap)\n- [ ] Google Search Console verified and sitemap submitted\n- [ ] Baseline bounce rate recorded at launch\n`,

    "BUILD_PLAN.md": `# BUILD_PLAN.md — Website Build Roadmap\n\n## Phase 1 — Design System & Shell ✅\n- [x] CSS design tokens (colour, font, spacing)\n- [x] Responsive layout shell (Header + Footer)\n- [x] Base components (Hero, FeatureCard, CTAButton)\n\n## Phase 2 — Pages & Content (Current)\n- [ ] Write all copy BEFORE designing (headline, CTA, social proof)\n- [ ] Build all pages from CONTENT_MAP.md\n- [ ] Add real images (WebP, < 100 KB each)\n- [ ] Verify each page has a visible above-the-fold CTA\n\n## Phase 3 — Forms & Lead Capture\n- [ ] Contact form with client-side validation\n- [ ] Connect to Formspree or EmailJS (no backend needed)\n- [ ] Success and error states on form submission\n- [ ] Honeypot spam protection\n\n## Phase 4 — SEO & Performance\n- [ ] Unique title + meta description on every page\n- [ ] Open Graph tags for social sharing\n- [ ] Generate sitemap.xml\n- [ ] Run Lighthouse — fix all issues blocking > 90\n- [ ] Compress images to WebP\n\n## Phase 5 — Deploy & Analytics\n- [ ] Deploy to Vercel or Netlify\n- [ ] Add custom domain + HTTPS\n- [ ] Install Plausible or Google Analytics 4\n- [ ] Track conversion event (form submit)\n- [ ] Submit sitemap to Google Search Console\n\n## Project Slug\n\`${slug}\`\n`,
  };
}

// ---------------------------------------------------------------------------
// WEB APP fallback — enhanced SPEC.md with DB schema and auth flow sections
// ---------------------------------------------------------------------------
function buildWebAppFallback(project) {
  const { ideaText, analysis, answers } = project;
  const appType = analysis?.appMeta?.label ?? "Web App";
  const icon    = analysis?.appMeta?.icon   ?? "⚡";
  const slug    = slugify(ideaText || "my-app");

  return {
    "SPEC.md": `# SPEC.md — Web App Specification\n\n## ${icon} App Type\n**${appType}**\n\n## 🎯 Core Idea\n${ideaText}\n\n## ⚠️ Hidden Complexity Warning\n${analysis?.warning ?? "_None identified._"}\n\n## ✅ Clarification Answers\n${formatAnswers(answers)}\n\n## 🗄️ Database Schema\n_Define your tables before writing any code. This is your contract._\n\n\`\`\`sql\n-- Users table (always the first table)\nCREATE TABLE users (\n  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  email       TEXT UNIQUE NOT NULL,\n  password_hash TEXT NOT NULL,\n  created_at  TIMESTAMPTZ DEFAULT now(),\n  updated_at  TIMESTAMPTZ DEFAULT now()\n);\n\n-- Core resource table (rename to match your domain)\nCREATE TABLE resources (\n  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  title       TEXT NOT NULL,\n  body        TEXT,\n  status      TEXT DEFAULT 'draft' CHECK (status IN ('draft','published','archived')),\n  created_at  TIMESTAMPTZ DEFAULT now(),\n  updated_at  TIMESTAMPTZ DEFAULT now()\n);\n\n-- Add indexes for common queries\nCREATE INDEX ON resources (user_id);\nCREATE INDEX ON resources (status);\n\`\`\`\n\n## 🔐 Authentication Flow\n\`\`\`\nSign Up:\n  POST /api/auth/register\n  { email, password } → hash password → insert user → return JWT\n\nLogin:\n  POST /api/auth/login\n  { email, password } → verify hash → return JWT (or set HTTP-only cookie)\n\nProtected Request:\n  Header: Authorization: Bearer <jwt>\n  → middleware verifies JWT → attaches user to req.user\n\nLogout:\n  POST /api/auth/logout → clear cookie / invalidate token\n\`\`\`\n\n## 🔒 Auth Rules\n- Never store plain-text passwords\n- Use bcrypt or Argon2 with cost factor ≥ 12\n- JWTs expire in 24 hours; refresh tokens expire in 30 days\n- All user data is scoped to \`user_id\` — users never see each other's data\n\n## 🏗️ Summary\n${analysis?.summary ?? "_Pending._"}\n\n---\n_Generated by Project Brain Web App Mode (offline fallback)._\n`,
    "RULES.md":      `# RULES.md — Web App Constraints\n\n## Scope\n- Build only what is defined in SPEC.md.\n- Auth is Phase 1 — no user data stored before auth is complete.\n\n## Stack\n- App Type: **${appType}**\n- Frontend: React + Vite + Tailwind CSS\n- Backend: Node.js / Express\n- Database: PostgreSQL (Replit DB or Neon)\n- Auth: Replit Auth or Clerk\n\n## Non-Negotiable Rules\n1. DB schema defined before any feature code\n2. Every API route validates its inputs (Zod or express-validator)\n3. All routes that read/write user data require \`requireAuth\` middleware\n4. All errors logged — no silent failures\n5. Env vars for all secrets — never committed to Git\n\n## Quality Gates\n- No feature ships without a TEST_PLAN entry\n- All routes documented in APP_MAP.md\n`,
    "BUILD_PLAN.md": `# BUILD_PLAN.md — Web App Roadmap\n\n## Phase 1 — Foundation ✅\n- [x] DB schema defined and seeded\n- [x] App shell with placeholder routes\n- [x] ORM/Prisma schema mirrors SQL\n\n## Phase 2 — Authentication (Current)\n- [ ] Sign-up route + email/password hashing\n- [ ] Login route + session/JWT\n- [ ] \`requireAuth\` middleware\n- [ ] Protected routes redirect unauthenticated users\n\n## Phase 3 — Core Feature\n- [ ] CRUD API routes for primary resource\n- [ ] Frontend UI for primary flow\n- [ ] Data scoped to authenticated user\n\n## Phase 4 — Polish\n- [ ] Loading skeletons\n- [ ] Error states (no blank screens)\n- [ ] Empty states for new users\n- [ ] Mobile responsiveness\n\n## Phase 5 — Ship\n- [ ] Production DB + migrations\n- [ ] Env vars in Replit Deployments secrets\n- [ ] Error monitoring (Sentry)\n- [ ] Health check endpoint\n\n## Project Slug\n\`${slug}\`\n`,
    "TEST_PLAN.md":  `# TEST_PLAN.md — Testing Strategy\n\n## Auth Tests\n- [ ] Sign-up with valid email creates user in DB\n- [ ] Sign-up with duplicate email returns 409\n- [ ] Login with correct credentials returns token\n- [ ] Login with wrong password returns 401\n- [ ] Protected route returns 401 without token\n\n## Core Feature Tests\n- [ ] Create resource — returns 201 + created object\n- [ ] Read resource — returns only current user's data\n- [ ] Update resource — changes persist after reload\n- [ ] Delete resource — row removed from DB\n\n## E2E (Playwright)\n- [ ] Sign up → verify email → log in → create resource → log out → log in again → resource still exists\n- [ ] Unauthenticated visit to /dashboard → redirected to /login\n- [ ] Invalid form inputs show validation messages, not errors\n`,
    "APP_MAP.md":    `# APP_MAP.md — Architecture\n\n## Frontend Routes\n| Path | Component | Auth Required |\n|------|-----------|---------------|\n| / | Landing | No |\n| /login | Login | No |\n| /signup | Signup | No |\n| /dashboard | Dashboard | Yes |\n| /settings | Settings | Yes |\n\n## Backend API\n| Method | Route | Auth | Description |\n|--------|-------|------|-------------|\n| POST | /api/auth/register | No | Create account |\n| POST | /api/auth/login | No | Get token |\n| POST | /api/auth/logout | Yes | Invalidate token |\n| GET | /api/resources | Yes | List user resources |\n| POST | /api/resources | Yes | Create resource |\n| PATCH | /api/resources/:id | Yes | Update resource |\n| DELETE | /api/resources/:id | Yes | Delete resource |\n| GET | /api/health | No | Health check |\n\n## Data Flow\nClient → fetch with Bearer token → Express route → \`requireAuth\` middleware → controller → Drizzle/Prisma query → PostgreSQL → JSON response → React state update\n\n## Project Slug\n\`${slug}\`\n`,
  };
}

// ---------------------------------------------------------------------------
// generateSpecPack — routes to the correct generator based on mode.
//
// Mode resolution priority: explicit isGameMode flag > keyword detection
// Website mode: generated locally (correct file set guaranteed)
// Game mode: calls backend with isGame:true flag (from previous session)
// WebApp mode: calls backend with mode:"webapp" for enhanced SPEC.md
// Standard mode: calls backend with standard prompt
// ---------------------------------------------------------------------------
export async function generateSpecPack(project) {
  const isGame    = Boolean(project.isGameMode);
  const textMode  = detectMode(project.ideaText ?? "");
  const mode      = isGame ? "game" : (project.mode ?? textMode);

  // Website mode — always generated locally (avoids wrong file set from backend)
  if (mode === "website") {
    return buildWebsitePack(project);
  }

  try {
    const response = await fetch("/api/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ project, isGame: mode === "game", mode }),
    });

    if (!response.ok) {
      const body = await response.json().catch(() => ({}));
      throw new Error(body.error ?? `Server returned ${response.status}`);
    }

    return await response.json();
  } catch (err) {
    if (err instanceof TypeError) {
      console.warn("[generateSpecPack] API server unreachable, using local fallback:", err.message);
      if (mode === "game")   return buildFallbackGamePack(project);
      if (mode === "webapp") return buildWebAppFallback(project);
      return buildFallbackSpecPack(project);
    }
    throw err;
  }
}
