const fs = require('fs');
const F = 'artifacts/promptmegood/index.html';
fs.copyFileSync(F, F + '.bak.' + Date.now());
let h = fs.readFileSync(F, 'utf8');
const css = `\n    /* ── Mode Switch ── */\n    .mode-switch{display:flex;gap:0;background:var(--color-surface-2);border:1px solid var(--color-border);border-radius:var(--radius-full);padding:4px;margin-bottom:var(--space-5);width:100%;max-width:360px}\n    .mode-switch-btn{flex:1;padding:10px 16px;border:none;border-radius:var(--radius-full);font-size:var(--text-sm);font-weight:600;cursor:pointer;background:transparent;color:var(--color-text-muted);transition:all 180ms ease;display:flex;align-items:center;justify-content:center;gap:6px}\n    .mode-switch-btn.active{background:var(--color-primary);color:#fff;box-shadow:var(--shadow-sm)}\n    .mode-switch-btn:not(.active):hover{color:var(--color-text);background:var(--color-surface)}\n    body.image-mode .builder-transition{display:none}\n    body.image-mode #generateBtn{display:none}\n    body.image-mode #image-generate-btn{display:flex!important}\n    body.image-mode .demo-stack,body.image-mode #random-prompt,body.image-mode #advanced-options,body.image-mode .guided-cta-row,body.image-mode .weekly-goal-pin,body.image-mode #auto-optimize-row,body.image-mode #tour-step-settings,body.image-mode .settings-panel{display:none!important}\n    body.image-mode .image-mode-hint{display:block!important}\n    body:not(.image-mode) #imageResultSection{display:none!important}\n    body:not(.image-mode) #image-generate-btn{display:none!important}\n    .image-mode-hint{display:none;font-size:var(--text-sm);color:var(--color-text-muted);margin-bottom:var(--space-3);padding:10px 14px;background:color-mix(in srgb,var(--color-primary) 8%,var(--color-surface));border-radius:var(--radius-md);border-left:3px solid var(--color-primary);line-height:1.5}\n    #image-generate-btn{display:none;width:100%;padding:14px;font-size:var(--text-base);font-weight:700;border-radius:var(--radius-full);border:none;background:var(--color-primary);color:#fff;cursor:pointer;align-items:center;justify-content:center;gap:8px;transition:opacity 180ms ease;margin-bottom:var(--space-2)}\n    #image-generate-btn:disabled{opacity:.65;cursor:not-allowed}\n    .image-result-section{margin-top:var(--space-4)}\n    .image-result-wrap{width:100%;background:var(--color-surface-2);border-radius:var(--radius-lg);overflow:hidden;border:1px solid var(--color-border);min-height:200px;display:flex;align-items:center;justify-content:center;margin-bottom:var(--space-3)}\n    .image-result-wrap img{display:block;width:100%;height:auto;border-radius:var(--radius-lg)}\n    .image-spinner{width:36px;height:36px;border:3px solid var(--color-border);border-top-color:var(--color-primary);border-radius:50%;animation:imgSpin .8s linear infinite;margin:0 auto 1rem}\n    @keyframes imgSpin{to{transform:rotate(360deg)}}\n    /* ── End Mode Switch ── */`;
const si = h.lastIndexOf('</style>', h.indexOf('</head>'));
if(si!==-1) h=h.slice(0,si)+css+h.slice(si);
const modeSwitch = `\n          <div class="mode-switch" id="modeSwitch" role="group" aria-label="Choose what to create">\n            <button class="mode-switch-btn active" id="writeModeBtn" type="button" onclick="setMode('write')">\u270d\ufe0f Write something</button>\n            <button class="mode-switch-btn" id="imageModeBtn" type="button" onclick="setMode('image')">\ud83c\udfa8 Create an image</button>\n          </div>\n          <p class="image-mode-hint">Describe the image you want \u2014 plain English. We\u2019ll turn it into a professional DALL\u00b7E\u00a03 prompt automatically.</p>`;
h=h.replace('<div class="panel-head panel-head-row">',modeSwitch+'\n          <div class="panel-head panel-head-row">');
h=h.replace('<button class="btn btn-primary" type="submit" id="generateBtn">Generate Prompt</button>','<button class="btn btn-primary" type="submit" id="generateBtn">Generate Prompt</button>\n                <button type="button" id="image-generate-btn" onclick="runImageGeneration()">\ud83c\udfa8 Generate Image</button>');
if(!h.includes('imageResultSection')){
  const imgSection=`\n            <div class="image-result-section" id="imageResultSection" hidden>\n              <div class="run-section-divider"></div>\n              <h3 class="run-section-title">Your generated image</h3>\n              <div class="image-result-wrap" id="imageResultWrap"><div style="padding:2rem;color:var(--color-text-faint);font-size:.9rem;text-align:center">Your image will appear here</div></div>\n              <div style="display:flex;gap:.5rem;flex-wrap:wrap">\n                <a id="imageDownloadBtn" href="" download="promptmegood-image.png" class="btn btn-primary" style="display:none;text-decoration:none">\u2b07 Download</a>\n                <button class="btn btn-secondary" type="button" onclick="runImageGeneration()">Generate another</button>\n              </div>\n              <p class="run-section-meta" style="margin-top:.5rem">DALL\u00b7E 3 \u00b7 Free during Early access \u00b7 ~10 seconds</p>\n            </div>`;
  h=h.replace('<div class="save-tip" id="save-tip"',imgSection+'\n            <div class="save-tip" id="save-tip"');
}
const js=`\n<script>\n(function(){\n  window.setMode=function(mode){\n    var isImg=mode==='image';\n    document.body.classList.toggle('image-mode',isImg);\n    document.getElementById('writeModeBtn').classList.toggle('active',!isImg);\n    document.getElementById('imageModeBtn').classList.toggle('active',isImg);\n    var goal=document.getElementById('goal');\n    if(goal)goal.placeholder=isImg?'A woman walking through rainy Tokyo at night, cinematic\u2026':'I need to make money online fast using skills I already have\u2026';\n    var title=document.getElementById('builder-title');\n    if(title)title.textContent=isImg?'Create an image':'Build your prompt';\n    if(!isImg){var sec=document.getElementById('imageResultSection');if(sec)sec.hidden=true;}\n  };\n  window.runImageGeneration=async function(){\n    var goal=document.getElementById('goal');\n    var desc=((goal&&goal.value)||'').trim();\n    if(!desc){alert('Describe the image you want first, then click Generate Image.');return}\n    var sec=document.getElementById('imageResultSection'),wrap=document.getElementById('imageResultWrap'),dl=document.getElementById('imageDownloadBtn'),btn=document.getElementById('image-generate-btn');\n    if(sec)sec.hidden=false;\n    if(wrap)wrap.innerHTML='<div style="text-align:center;padding:2rem"><div class="image-spinner"></div><p style="color:var(--color-text-muted);font-size:.9rem">Creating with DALL\u00b7E 3\u2026<br><small>About 10 seconds</small></p></div>';\n    if(dl)dl.style.display='none';\n    if(btn){btn.disabled=true;btn.innerHTML='\u23f3 Generating\u2026'}\n    setTimeout(function(){if(sec)sec.scrollIntoView({behavior:'smooth',block:'center'})},150);\n    try{\n      var res=await fetch('/api/image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:desc})});\n      var data=await res.json();\n      if(!res.ok||!data.url){if(wrap)wrap.innerHTML='<div style="padding:2rem;text-align:center;color:var(--color-text-muted)">\u26a0\ufe0f '+(data.error||'Failed. Try again.')+'</div>';return}\n      if(wrap){wrap.innerHTML='';var img=document.createElement('img');img.src=data.url;img.alt='AI generated image';img.onload=function(){if(sec)sec.scrollIntoView({behavior:'smooth',block:'center'})};wrap.appendChild(img)}\n      if(dl){dl.href=data.url;dl.style.display='inline-flex'}\n    }catch(e){if(wrap)wrap.innerHTML='<div style="padding:2rem;text-align:center;color:var(--color-text-muted)">\u26a0\ufe0f Network error. Try again.</div>'}\n    finally{if(btn){btn.disabled=false;btn.innerHTML='\ud83c\udfa8 Generate Image'}}\n  };\n  window.generateImage=window.runImageGeneration;\n})();\n</script>`;
h=h.replace('</body>',js+'\n</body>');
fs.writeFileSync(F,h);
console.log('Done. Mode switch added.');
