const fs = require('fs');
const FILE = 'artifacts/promptmegood/index.html';
if (!fs.existsSync(FILE)) { console.error('ERROR: Cannot find ' + FILE); process.exit(1); }
fs.copyFileSync(FILE, FILE + '.bak.' + Date.now());
let h = fs.readFileSync(FILE, 'utf8');
if (!h.includes('imageResultSection')) {
  const section = `\n            <div class="image-result-section" id="imageResultSection" hidden>\n              <div class="run-section-divider"></div>\n              <h3 class="run-section-title">Your generated image</h3>\n              <p class="run-section-helper">Created by DALL·E 3 — right here in the app.</p>\n              <div class="image-result-wrap" id="imageResultWrap"><div class="image-placeholder">Your image will appear here</div></div>\n              <div class="image-result-actions">\n                <a id="imageDownloadBtn" href="" download="promptmegood-image.png" class="btn btn-primary" style="display:none;text-decoration:none;">⬇ Download</a>\n                <button class="btn btn-secondary" type="button" id="imageAgainBtn" onclick="generateImage()">Generate another</button>\n              </div>\n              <p class="run-section-meta">DALL·E 3 · Free during Early access</p>\n            </div>`;
  h = h.replace('<div class="save-tip" id="save-tip"', section + '\n\n            <div class="save-tip" id="save-tip"');
}
if (!h.includes('imageBtn')) {
  h = h.replace('<button class="btn btn-primary run-btn" type="button" id="runBtn" onclick="runWithAI()">', '<button class="btn btn-secondary run-btn" type="button" id="imageBtn" onclick="generateImage()" style="display:none;">🎨 Generate Image</button>\n              <button class="btn btn-primary run-btn" type="button" id="runBtn" onclick="runWithAI()">');
}
const css = `\n    .image-result-section{margin-top:var(--space-4)}.image-result-wrap{width:100%;background:var(--color-surface-2);border-radius:var(--radius-lg);overflow:hidden;border:1px solid var(--color-border);min-height:200px;display:flex;align-items:center;justify-content:center;margin-bottom:var(--space-3)}.image-placeholder{font-size:var(--text-sm);color:var(--color-text-faint);padding:var(--space-8)}#imageResultWrap img{display:block;width:100%;height:auto;border-radius:var(--radius-lg)}.image-result-actions{display:flex;gap:var(--space-2);flex-wrap:wrap;margin-bottom:var(--space-2)}.image-generating-state{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:var(--space-3);padding:var(--space-8);color:var(--color-text-muted);font-size:var(--text-sm);text-align:center}.image-spinner{width:36px;height:36px;border:3px solid var(--color-border);border-top-color:var(--color-primary);border-radius:50%;animation:imgSpin 0.8s linear infinite}@keyframes imgSpin{to{transform:rotate(360deg)}}body.photo-mode-active #imageBtn{display:inline-flex!important}body.photo-mode-active #runBtn{display:none!important}`;
const idx = h.lastIndexOf('</style>', h.indexOf('</head>'));
if (idx !== -1) h = h.slice(0, idx) + css + h.slice(idx);
const js = `\n  <script>\n  (function(){\n    function $(id){return document.getElementById(id)}\n    var pt=$('photoMode');\n    if(pt){pt.addEventListener('change',function(){document.body.classList.toggle('photo-mode-active',pt.checked)});document.body.classList.toggle('photo-mode-active',pt.checked)}\n    window.generateImage=async function(){\n      var rb=$('resultBox'),prompt=((rb&&(rb.textContent||rb.innerText))||'').trim();\n      if(!prompt){alert('Generate a prompt first, then click Generate Image.');return}\n      var sec=$('imageResultSection'),wrap=$('imageResultWrap'),dl=$('imageDownloadBtn'),again=$('imageAgainBtn'),btn=$('imageBtn');\n      if(sec)sec.hidden=false;\n      if(wrap)wrap.innerHTML='<div class="image-generating-state"><div class="image-spinner"></div><span>Creating your image…<br><small>About 10 seconds</small></span></div>';\n      if(dl)dl.style.display='none';\n      if(btn){btn.disabled=true;btn.innerHTML='⏳ Generating…'}\n      if(again)again.disabled=true;\n      setTimeout(function(){if(sec)sec.scrollIntoView({behavior:'smooth',block:'center'})},100);\n      try{\n        var res=await fetch('/api/image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:prompt})});\n        var data=await res.json();\n        if(!res.ok||!data.url){if(wrap)wrap.innerHTML='<div class="image-generating-state"><span>⚠️ '+(data.error||'Failed. Try again.')+'</span></div>';return}\n        if(wrap){wrap.innerHTML='';var img=document.createElement('img');img.src=data.url;img.alt='AI generated image';img.onload=function(){if(sec)sec.scrollIntoView({behavior:'smooth',block:'center'})};wrap.appendChild(img)}\n        if(dl){dl.href=data.url;dl.style.display='inline-flex'}\n      }catch(e){if(wrap)wrap.innerHTML='<div class="image-generating-state"><span>⚠️ Network error. Try again.</span></div>'}\n      finally{if(btn){btn.disabled=false;btn.innerHTML='🎨 Generate Image'}if(again)again.disabled=false}\n    }\n  })()\n  </script>`;
h = h.replace('</body>', js + '\n</body>');
fs.writeFileSync(FILE, h);
console.log('Done. Image generation added.');
