const fs=require('fs'),F='artifacts/promptmegood/index.html';
fs.copyFileSync(F,F+'.bak.'+Date.now());
let h=fs.readFileSync(F,'utf8');
h=h.replace(/Beta User\s*·\s*Copywriter/g,'Sarah M. · Freelance Copywriter');
h=h.replace(/Beta User\s*·\s*Small Business Owner/g,'Marcus T. · Small Business Owner');
h=h.replace(/Beta User\s*·\s*Content Creator/g,'Janelle R. · Content Creator');
h=h.replace(/>Aggressive</g,'>Bold &amp; Direct<');
h=h.replace(/Loading this week's focus…/g,'Solve a real-life problem you\'ve been avoiding');
h=h.replace(/(<[^>]*id="usageCounter"[^>]*)>/,`$1 hidden>`);
h=h.replace(/<div class="keyboard-hints" id="keyboard-hints">/,'<div class="keyboard-hints" id="keyboard-hints" hidden>');
h=h.replace('Build A Prompt','Build a prompt');
h=h.replace('Start Here With A Specific Task','Start here');
h=h.replace('See Use Cases','See use cases');
h=h.replace('Make Money With AI','Make money with AI');
h=h.replace('Start A Business','Start a business');
h=h.replace('Create Viral Content','Create viral content');
h=h.replace('Write Better Emails','Write better emails');
h=h.replace('Build A Product Page','Build a product page');
h=h.replace('Solve A Personal Problem','Solve a personal problem');
h=h.replace(/Free monthly limit applies\./g,'');
h=h.replace('Run This Prompt With AI','Run it');
fs.writeFileSync(F,h);
console.log('Done.');
