// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chassis/AllChassis.tsx": () => import("../components/mockups/chassis/AllChassis.tsx"),
  "./components/mockups/chassis/ExpertCenter.tsx": () => import("../components/mockups/chassis/ExpertCenter.tsx"),
  "./components/mockups/chassis/HomepageHero.tsx": () => import("../components/mockups/chassis/HomepageHero.tsx"),
  "./components/mockups/chassis/Marketing.tsx": () => import("../components/mockups/chassis/Marketing.tsx"),
  "./components/mockups/chassis/PhotoSuite.tsx": () => import("../components/mockups/chassis/PhotoSuite.tsx"),
  "./components/mockups/chassis/Pricing.tsx": () => import("../components/mockups/chassis/Pricing.tsx"),
  "./components/mockups/chassis/ResultPanel.tsx": () => import("../components/mockups/chassis/ResultPanel.tsx"),
  "./components/mockups/chassis/WelcomeBack.tsx": () => import("../components/mockups/chassis/WelcomeBack.tsx"),
  "./components/mockups/chassis/WorkstationHeader.tsx": () => import("../components/mockups/chassis/WorkstationHeader.tsx")
};
