// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chassis/AllChassis.tsx": () => import("../components/mockups/chassis/AllChassis.tsx"),
  "./components/mockups/chassis/ExpertCenter.tsx": () => import("../components/mockups/chassis/ExpertCenter.tsx"),
  "./components/mockups/chassis/HomepageHero.tsx": () => import("../components/mockups/chassis/HomepageHero.tsx"),
  "./components/mockups/chassis/Marketing.tsx": () => import("../components/mockups/chassis/Marketing.tsx"),
  "./components/mockups/chassis/PhotoSuite.tsx": () => import("../components/mockups/chassis/PhotoSuite.tsx"),
  "./components/mockups/chassis/Pricing.tsx": () => import("../components/mockups/chassis/Pricing.tsx"),
  "./components/mockups/chassis/ResultPanel.tsx": () => import("../components/mockups/chassis/ResultPanel.tsx"),
  "./components/mockups/chassis/WelcomeBack.tsx": () => import("../components/mockups/chassis/WelcomeBack.tsx"),
  "./components/mockups/chassis/WorkstationHeader.tsx": () => import("../components/mockups/chassis/WorkstationHeader.tsx"),
  "./components/mockups/chassis/v2/HeroChatGPTDark.tsx": () => import("../components/mockups/chassis/v2/HeroChatGPTDark.tsx"),
  "./components/mockups/chassis/v2/HeroChatGPTEditorial.tsx": () => import("../components/mockups/chassis/v2/HeroChatGPTEditorial.tsx"),
  "./components/mockups/chassis/v2/HeroClaudeDark.tsx": () => import("../components/mockups/chassis/v2/HeroClaudeDark.tsx"),
  "./components/mockups/chassis/v2/HeroClaudeWarm.tsx": () => import("../components/mockups/chassis/v2/HeroClaudeWarm.tsx"),
  "./components/mockups/chassis/v2/HeroEditorialPure.tsx": () => import("../components/mockups/chassis/v2/HeroEditorialPure.tsx"),
  "./components/mockups/chassis/v2/HeroLinearGlass.tsx": () => import("../components/mockups/chassis/v2/HeroLinearGlass.tsx"),
  "./components/mockups/chassis/v2/HeroWarmDarkHybrid.tsx": () => import("../components/mockups/chassis/v2/HeroWarmDarkHybrid.tsx"),
  "./components/mockups/chassis/v2/MasterPlanWorkspace.tsx": () => import("../components/mockups/chassis/v2/MasterPlanWorkspace.tsx"),
  "./components/mockups/chassis/v2/WorkstationChassisV2.tsx": () => import("../components/mockups/chassis/v2/WorkstationChassisV2.tsx"),
  "./components/mockups/chassis/v2/WorkstationChassisV3.tsx": () => import("../components/mockups/chassis/v2/WorkstationChassisV3.tsx"),
  "./components/mockups/chassis/v2/WorkstationG.tsx": () => import("../components/mockups/chassis/v2/WorkstationG.tsx")
};
