export const TEMPLATES = [
  // ── WEB APP ──────────────────────────────────────────────────────────────
  {
    id:            "saas-dashboard",
    name:          "SaaS Dashboard",
    description:   "Subscription-based tool with user accounts and analytics",
    category:      "web_app",
    categoryLabel: "Web App",
    emoji:         "📊",
    complexity:    "Intermediate",
    projectType:   "app",
    starterIdea:   "I want to build a SaaS dashboard product. It will have user authentication, subscription billing (likely Stripe), a main dashboard with charts and metrics, and an account/settings page. Users sign up, choose a plan, and access data specific to their account.",
    systemHint:    "The user is building a SaaS Dashboard — a subscription-based web app with user accounts, recurring billing, and a data/analytics dashboard. Expect: auth (login/signup), subscription tiers, a dashboard with charts or KPIs, user settings, and potentially an admin panel. Tech considerations: Stripe for billing, role-based access, secure multi-tenant data.",
  },
  {
    id:            "marketplace",
    name:          "Marketplace",
    description:   "Buyers and sellers, listings, and payment processing",
    category:      "web_app",
    categoryLabel: "Web App",
    emoji:         "🛒",
    complexity:    "Advanced",
    projectType:   "app",
    starterIdea:   "I want to build a marketplace where buyers and sellers can connect. Sellers list items or services with prices and photos. Buyers browse, search, and purchase. Payments go through the platform and are paid out to sellers. Both sides have profiles and dashboards.",
    systemHint:    "The user is building a Marketplace — a two-sided platform with buyer and seller roles. Expect: seller listings/inventory, buyer browsing/search, payments with split payouts (Stripe Connect), reviews/ratings, messaging between parties, and trust/moderation features. Complex auth with two distinct user roles.",
  },
  {
    id:            "booking-app",
    name:          "Booking App",
    description:   "Appointments, availability calendar, and scheduling",
    category:      "web_app",
    categoryLabel: "Web App",
    emoji:         "📅",
    complexity:    "Intermediate",
    projectType:   "app",
    starterIdea:   "I want to build a booking and scheduling app. Service providers set their availability. Customers browse providers, pick a time slot, and book an appointment. Both get confirmations and reminders. Providers can manage their calendar and see upcoming bookings.",
    systemHint:    "The user is building a Booking App — appointment scheduling with calendar availability. Expect: provider availability management, time-slot booking, calendar views, email/SMS confirmations and reminders, payment at booking or on arrival, and cancellation/rescheduling flows.",
  },
  {
    id:            "community-platform",
    name:          "Community Platform",
    description:   "User profiles, posts, comments, and social interaction",
    category:      "web_app",
    categoryLabel: "Web App",
    emoji:         "🏘️",
    complexity:    "Advanced",
    projectType:   "app",
    starterIdea:   "I want to build a community platform where members can create profiles, post content, comment, and interact with each other. There will be categories or channels, upvoting or reactions, moderation tools, and notifications for activity.",
    systemHint:    "The user is building a Community Platform — a social/forum product with user profiles, content creation, and interaction. Expect: user profiles, post/thread creation, comments/replies, voting/reactions, categories or channels, notifications, moderation tools, and search.",
  },

  // ── WEBSITE ───────────────────────────────────────────────────────────────
  {
    id:            "landing-page",
    name:          "Landing Page",
    description:   "Hero, features, pricing section, and a conversion CTA",
    category:      "website",
    categoryLabel: "Website",
    emoji:         "🪟",
    complexity:    "Beginner",
    projectType:   "website",
    starterIdea:   "I want to build a marketing landing page for a product or service. It should have a hero section with a headline and CTA, a features section, social proof or testimonials, a pricing section, and a footer. The goal is to get visitors to sign up or contact us.",
    systemHint:    "The user is building a Marketing Landing Page. Expect: hero section (headline, sub-headline, CTA button), feature highlights (3–6 items), social proof (testimonials or logos), pricing tiers, FAQ, and a contact or signup CTA. Conversion-focused design.",
  },
  {
    id:            "portfolio",
    name:          "Portfolio",
    description:   "Work samples, about page, and contact form",
    category:      "website",
    categoryLabel: "Website",
    emoji:         "🎨",
    complexity:    "Beginner",
    projectType:   "website",
    starterIdea:   "I want to build a personal portfolio website to showcase my work. It should have an about section, a gallery or list of projects with descriptions and links, my skills or services, and a contact form or email link.",
    systemHint:    "The user is building a Portfolio Website. Expect: an about/bio section, project showcase with images and descriptions, skills or services list, testimonials (optional), and a contact form. Focus on visual presentation and clean navigation.",
  },
  {
    id:            "blog",
    name:          "Blog",
    description:   "Articles, categories, author profile, and RSS",
    category:      "website",
    categoryLabel: "Website",
    emoji:         "✍️",
    complexity:    "Beginner",
    projectType:   "website",
    starterIdea:   "I want to build a blog where I can publish articles. It should have a homepage with recent posts, individual article pages, categories or tags, an about/author page, and ideally a newsletter signup or RSS feed.",
    systemHint:    "The user is building a Blog. Expect: article listing page, individual post pages with rich content, categories/tags, author profile, RSS feed, newsletter signup (optional), and potentially a CMS backend or markdown-based content system.",
  },

  // ── GAME ─────────────────────────────────────────────────────────────────
  {
    id:            "platformer",
    name:          "2D Platformer",
    description:   "Side-scrolling levels, player movement, and score",
    category:      "game",
    categoryLabel: "Game",
    emoji:         "🎮",
    complexity:    "Intermediate",
    projectType:   "game",
    starterIdea:   "I want to build a 2D side-scrolling platformer game. The player runs, jumps, and avoids obstacles across levels. There will be collectibles, enemies, a score system, and multiple levels with increasing difficulty.",
    systemHint:    "The user is building a 2D Platformer game. Expect: player controller (run, jump, double-jump), level design with platforms and obstacles, enemies with basic AI, collectibles, score/lives system, multiple levels or procedural generation, sound effects, and a game loop (start, play, game over, restart).",
  },
  {
    id:            "puzzle-game",
    name:          "Puzzle Game",
    description:   "Grid-based logic puzzle with progression and hints",
    category:      "game",
    categoryLabel: "Game",
    emoji:         "🧩",
    complexity:    "Beginner",
    projectType:   "game",
    starterIdea:   "I want to build a puzzle game. The game is grid-based with a logic mechanic the player figures out. It has multiple levels that get progressively harder, a hint system, move counter or timer, and a level completion screen.",
    systemHint:    "The user is building a Puzzle Game. Expect: grid-based game board, core puzzle mechanic (match, slide, connect, or similar), level progression with increasing difficulty, move counter or timer, hint system, win/lose detection, level completion screen, and local score or best-time tracking.",
  },
  {
    id:            "trivia-game",
    name:          "Trivia / Quiz Game",
    description:   "Questions, multiple-choice answers, and a leaderboard",
    category:      "game",
    categoryLabel: "Game",
    emoji:         "🏆",
    complexity:    "Beginner",
    projectType:   "game",
    starterIdea:   "I want to build a trivia or quiz game. Players answer multiple-choice questions on a topic, with a timer per question. At the end they see their score, and there's a leaderboard showing high scores.",
    systemHint:    "The user is building a Trivia/Quiz Game. Expect: question bank (categorized or random), multiple-choice answer options, per-question timer, score calculation (with speed bonus optionally), final score screen, leaderboard (local or persisted), and optionally: categories, difficulty levels, and multiplayer.",
  },

  // ── MOBILE ────────────────────────────────────────────────────────────────
  {
    id:            "habit-tracker",
    name:          "Habit Tracker",
    description:   "Daily goals, streaks, completion tracking, and reminders",
    category:      "mobile",
    categoryLabel: "Mobile App",
    emoji:         "✅",
    complexity:    "Beginner",
    projectType:   "app",
    starterIdea:   "I want to build a mobile habit tracker app. Users add habits they want to build, check them off daily, see their streak, and get reminders. There will be a home screen with today's habits, a calendar view showing history, and stats.",
    systemHint:    "The user is building a Mobile Habit Tracker app. Expect: habit creation and management, daily completion check-off, streak counting, push notification reminders, a calendar or history view, progress stats, and a clean today/dashboard view. Likely React Native/Expo.",
  },
  {
    id:            "social-app",
    name:          "Social App",
    description:   "User profiles, a follow system, and a content feed",
    category:      "mobile",
    categoryLabel: "Mobile App",
    emoji:         "🧑‍🤝‍🧑",
    complexity:    "Advanced",
    projectType:   "app",
    starterIdea:   "I want to build a mobile social app. Users create profiles, post content (text/photos), follow each other, and see a personalized feed of posts from people they follow. They can like, comment, and share posts.",
    systemHint:    "The user is building a Mobile Social App. Expect: user profiles with avatars and bios, post creation (text + media), following/followers system, personalized feed, likes and comments, notifications, direct messaging (optional), and content moderation basics.",
  },
  {
    id:            "on-demand-service",
    name:          "On-Demand Service",
    description:   "Request, match with provider, and fulfillment flow",
    category:      "mobile",
    categoryLabel: "Mobile App",
    emoji:         "🚗",
    complexity:    "Advanced",
    projectType:   "app",
    starterIdea:   "I want to build an on-demand service app. Customers request a service, the system matches them with a nearby provider, the provider accepts, fulfills the service, and the customer pays and rates. Both sides have real-time status updates.",
    systemHint:    "The user is building an On-Demand Service App (Uber-style). Expect: dual roles (customer + provider), service request flow, matching/assignment logic, real-time location or status updates, in-app payments, rating/review system, and provider availability management.",
  },

  // ── AI / AUTOMATION ───────────────────────────────────────────────────────
  {
    id:            "ai-writing-tool",
    name:          "AI Writing Tool",
    description:   "User input, AI processing, and formatted output",
    category:      "ai",
    categoryLabel: "AI Tool",
    emoji:         "🤖",
    complexity:    "Intermediate",
    projectType:   "ai",
    starterIdea:   "I want to build an AI-powered writing tool. Users provide a prompt or some input, the AI processes it and returns a formatted result (e.g. essay, email, summary, code). Users can adjust settings, copy the output, save results, and build a history of past generations.",
    systemHint:    "The user is building an AI Writing Tool. Expect: text/prompt input with configuration options (tone, length, style), streaming or batched AI response, formatted output display, copy-to-clipboard, output history, user authentication (optional), and potentially usage/credit tracking.",
  },
  {
    id:            "data-pipeline",
    name:          "Data Pipeline",
    description:   "Input source, transformation logic, and output destination",
    category:      "ai",
    categoryLabel: "AI Tool",
    emoji:         "🔁",
    complexity:    "Advanced",
    projectType:   "ai",
    starterIdea:   "I want to build an automated data pipeline tool. Users connect an input source (file upload, API, or database), define transformation or processing steps (cleaning, formatting, AI enrichment), and route the output to a destination (download, API, another database).",
    systemHint:    "The user is building a Data Pipeline tool. Expect: input connectors (file upload, API, database), a step-based transformation UI, AI enrichment or processing steps, output/export options, pipeline run history, error handling and logging, and optionally scheduled runs.",
  },
  {
    id:            "chatbot",
    name:          "Chatbot",
    description:   "Conversation flow, knowledge base, and chat interface",
    category:      "ai",
    categoryLabel: "AI Tool",
    emoji:         "💬",
    complexity:    "Intermediate",
    projectType:   "ai",
    starterIdea:   "I want to build a custom chatbot. It has a chat interface where users ask questions and get answers. The bot is powered by an LLM and grounded in a custom knowledge base (documents, FAQs, or a database). It remembers conversation history within a session.",
    systemHint:    "The user is building a Chatbot. Expect: chat UI with message bubbles and input, LLM backend integration, knowledge base grounding (RAG with uploaded docs or a vector store), conversation history/session management, system prompt configuration, and potentially: user authentication and chat history persistence.",
  },
];

export const CATEGORY_LABELS = {
  all:     "All",
  web_app: "Web App",
  website: "Website",
  game:    "Game",
  mobile:  "Mobile App",
  ai:      "AI Tool",
};

export const CATEGORY_EMOJIS = {
  web_app: "🌐",
  website: "🪟",
  game:    "🎮",
  mobile:  "📱",
  ai:      "🤖",
};

export const COMPLEXITY_COLORS = {
  Beginner:     "text-success border-success/30 bg-success/10",
  Intermediate: "text-warning border-warning/30 bg-warning/10",
  Advanced:     "text-error border-error/30 bg-error/10",
};
